name: Terraform init
description: Plan the Terraform script and (optionally) upload the resulting artifact
inputs:
  aws-access-key-id:
    description:
    required: true
  aws-profile-name:
    description:
    required: true
  aws-region:
    description:
    required: false
    default: me-south-1
  aws-secret-access-key:
    description:
    required: true
  version:
    description: Terraform version to use
    required: false
    default: 1.0.11
  working-directory:
    description: Directory where to run the plan command
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.version }}

    - name: Add profile credentials to ~/.aws/credentials
      env:
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
      shell: bash
      run: |
        aws configure set aws_access_key_id ${{ inputs.aws-access-key-id }} --profile ${{ inputs.aws-profile-name }}
        aws configure set aws_secret_access_key ${{ inputs.aws-secret-access-key }} --profile ${{ inputs.aws-profile-name }}

    - name: Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform init
