name: Terraform init
description: Plan the Terraform script and (optionally) upload the resulting artifact
inputs:
  version:
    description: Terraform version to use
    required: false
    default: 1.1.5
  working-directory:
    description: Directory where to run the plan command
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.version }}

    - name: Init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform init
